### ISSUE TITLE
Not enough stars

### ISSUE THREAD

**Issue by caando** [et-irl/courserekt#4]
As of the time of opening this issue, the repo only has 12 stars, 4 away from the required 16 stars for GitHub's `Starstruck` badge. This is a very pressing issue. Please fix.

**Comment by et-irl** [comment]
Thank you for bringing this pressing matter to our attention. We understand the significance of the prestigious GitHub Starstruck badge and how it serves as a beacon of recognition.

Rest assured, our stellar engineering team is already working tirelessly to address this critical issue. We have initiated an elaborate star-generating algorithm that harnesses the power of quantum energy to rapidly increase our repository's star count.

As we accelerate through this project, attracting stars through day and night, we kindly ask for your utmost support. Help us spread the word about our repository, and encourage other developers to join our mission.

Together, we will transcend the stellar threshold and unlock the coveted Starstruck badge, firmly establishing our repository as a shining star in the open-source universe.

In the meantime, please keep an eye on our repository as we twinkle brighter each day. We appreciate your unrelenting understanding and collaboration.

**Comment by caando** [comment]
lgtm

**Comment by et-irl** [comment]
Hi, I am glad to inform you that this issue has been resolved. Thank you for your unending patience and understanding as we tireless worked during this relentless period.
